# -*- coding: utf-8 -*-
"""Deliverable_8_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvQOJwnsItuzvIQ-ZluzyyDNaCeXnA03
"""

import numpy as np

def random_list(size):
  list = []
  for i in range(size):
    list.append(np.random.randint(10,50))
    return list

def sum_random (list):
  sum = 0
  for i in range(len(list)):
    sum = sum + list[i]
    return sum

n = int(input("Enter some integar"))

MyList = random_list(n)
MyList

MySum = sum_random(MyList)
MySum

MyList2 = np.random.randint(10,50, n)
MyList2

MySum2 = sum(MyList2)
MySum2